import React from "react"
import Image from "next/image"

import { ClerkProvider } from "@clerk/nextjs"
import { Inter } from "next/font/google"
import type { Metadata } from "next"

import '../globals.css'

export const metadata: Metadata = {
    title: 'Auth',
    description: 'Generated by create next app'
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ 
    children 
}: {
    children: React.ReactNode
}) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={`${inter.className} bg-gradient-to-r from-gray-950 to-purple-950`}>
                    <div className="w-full flex justify-center items-center min-h-screen"> 
                        {children}
                        <Image src="/assets/login.svg" alt="image" width={500} height={500} className="max-lg:hidden"/>
                    </div>
                    <footer className="flex justify-center items-center relative">
                        <p className="text-purple-500 justify-center items-center absolute bottom-5"><span className="font-bold">ReCollect</span> | By Shubhanshu</p>
                    </footer>
                </body>
            </html>
        </ClerkProvider>
    )
}